version: 0.2
phases:
   pre-build:
    commands:
       - echo logging into amazon ECR...
       - $(aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 927599552380.dkr.ecr.ap-south-1.amazonaws.com)
    
   build:
     commands:
        - echo building the docker image..
        - docker build -t container-service .
        - docker tag container-service:latest 927599552380.dkr.ecr.ap-south-1.amazonaws.com/container-service:latest
        
   post_build:
     commands:
        - echo pushing the docker image....
        - docker push 927599552380.dkr.ecr.ap-south-1.amazonaws.com/container-service:latest
